#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2048M

#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

org.gradle.internal.http.socketTimeout=60000
org.gradle.internal.http.connectionTimeout=60000

#Room
kotlin.native.desableCompilerDaemon = true